### ISSUE TITLE
CoffeeScript -> plain js

### ISSUE THREAD

**Issue by zertosh** [StreamMachine/prometheus_client_nodejs#1]
I would love to contribute to this project, but CoffeeScript adds another layer of complexity that keeps devs like me from giving back. Please consider switching to plain js. It's just a suggestion - it's your project and you're free to do as you wish. Feel free to close this issue whenever :smile:

cc: @ewr

**Comment by ewr** [comment]
Thanks for the feedback. If you have specific functionality that you want to PR against the compiled JS I'd be glad to take a look at porting it over into the Coffeescript base. 

Do you have a fundamental issue with Coffeescript, or it just isn't your preferred way to do JS?

**Comment by mansona** [comment]
I would like to second @zertosh's request to change this to a pure JS repo, mainly because it is clear that the wider Javascript community has clearly voted against things like Coffeescript in favour of ES6 and related technologies. 

I would be happy to contribute to this repo to begin the conversion to ES6 syntax using something like babel if that is something you would be interested in?

**Comment by ewr** [comment]
Sure, I'd be open to that. I've only followed ES6 peripherally, but I guess we're getting closer and closer to that time when I need to be paying attention.

**Comment by mansona** [comment]
Great, well in that case I suppose we better add a meta issue that allows us to identify all the key parts of the library that need upgrading. I'll create it now as a new issue :+1:
